services:
  rebalance:
    build:
      context: .
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    restart: unless-stopped
    container_name: brice-tao-rebalance
    volumes:
      - ./.env:/app/.env:ro
      - ./logs:/app/logs
      - ./data:/app/data
